import { PublicMenu } from "@spaceorder/db/types";

export const MOCK_MENUS: PublicMenu[] = [
  {
    publicId: "1",
    name: "시그니처 아메리카노",
    price: 4500,
    sortOrder: 1,
    isAvailable: true,
    category: "커피",
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크를 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl:
      "https://images.unsplash.com/photo-1531835207745-506a1bc035d8?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "2",
    name: "카페 라떼",
    price: 5000,
    sortOrder: 3,
    isAvailable: true,
    category: "커피",
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크를 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl:
      "https://images.unsplash.com/photo-1729364983489-d4d569978fd7?q=80&w=1296&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "3",
    name: "카푸치노",
    price: 5500,
    sortOrder: 4,
    isAvailable: true,
    category: "커피",
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크와 초콜릿 시럽을 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl:
      "https://images.unsplash.com/photo-1534778101976-62847782c213?q=80&w=1287&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "4",
    name: "크로와상",
    sortOrder: 1,
    category: "디저트",
    isAvailable: true,
    price: 5000,
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크를 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl:
      "https://images.unsplash.com/photo-1681218079567-35aef7c8e7e4?q=80&w=2148&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "555",
    name: "치즈케이크",
    sortOrder: 2,
    category: "디저트",
    isAvailable: true,
    price: 6500,
    description: "부드러운 뉴욕 스타일 치즈케이크 작은 사이즈로만 제공됩니다.",
    imageUrl:
      "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?q=80&w=2340&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "5",
    name: "헤이즐넛 라떼",
    sortOrder: 2,
    category: "커피",
    isAvailable: true,
    price: 5000,
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크와 헤이즐넛 시럽을 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl: "/coffee_sample.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "66",
    name: "헤이즐넛 라떼",
    sortOrder: 7,
    category: "커피",
    isAvailable: true,
    price: 5000,
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크와 헤이즐넛 시럽을 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl: "/coffee_sample.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "77",
    name: "헤이즐넛 라떼",
    sortOrder: 8,
    category: "커피",
    isAvailable: true,
    price: 5000,
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크와 헤이즐넛 시럽을 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl: "/coffee_sample.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
  {
    publicId: "99",
    name: "헤이즐넛 라떼",
    sortOrder: 9,
    category: "커피",
    isAvailable: true,
    price: 5000,
    description:
      "진하면서도 부드러운 시그니처 리스트레토 3샷에 폼을 살짝 낸 스팀 밀크와 헤이즐넛 시럽을 더해 짙은 커피 풍미를 즐길 수 있는 코르타도입니다. 227ml(8 fl oz) 숏 사이즈로만 제공됩니다.",
    imageUrl: "/coffee_sample.jpg",
    createdAt: new Date(),
    updatedAt: new Date(),
    deletedAt: null,
    requiredOptions: null,
    customOptions: null,
  },
];
