import type { Metadata } from "next";
import { Inter, JetBrains_Mono } from "next/font/google";
import "@spaceorder/ui/globals.css";
import { NextThemeProviders } from "@/components/theme/ThemeProviders";
import TanstackProvider from "@spaceorder/api/core/TanstackProvider";
import React from "react";
import { OrderdeskAuthProvider } from "@/providers/OrderdeskAuthProvider";

const inter = Inter({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const jetbrainsMono = JetBrains_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${jetbrainsMono.variable} antialiased`}
      >
        <OrderdeskAuthProvider>
          <TanstackProvider>
            <NextThemeProviders>{children}</NextThemeProviders>
          </TanstackProvider>
        </OrderdeskAuthProvider>
      </body>
    </html>
  );
}
